### ISSUE TITLE
我感觉用casbin是多此一举

### ISSUE THREAD

**Issue by apple1563** [hailaz/gf-casbin-adapter#3]
比如我们想到给 api 设定权限，我们可以在数据库建立一个表，两个字段 role_id,跟api_id。
给角色分配权限的时候就往这个表里插入数据。
查询角色有无某api权限就去查这个表里面有没有两者的关联行数据。
casbin多此一举，简单问题复杂化。

**Comment by hailaz** [comment]
看需求办事
